name: Test WordPress plugin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |-
            extends: default
            rules:
              document-start:
                present: false
              truthy:
                check-keys: false
            ignore:
              - node_modules
              - vendor

  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint PHP files
        uses: overtrue/phplint@9.1.2

  composer-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - run: test ! -f composer.json || composer validate --strict

  javascript-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Enabled Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Run JS unit tests
        run: yarn test:unit

  wordpress-phpunit:
    name: WordPress PHPUnit
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Enabled Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Compile assets
        run: yarn build

      - name: Run tests
        id: test
        uses: >-  # v2.0.4
          holyhope/test-wordpress-plugin-github-action@1e7895de5852603e93a8e92afe9d008b76521355
        with:
          plugin_slug: customer-data
          php_version: '8.3'

      - name: JUnit Report
        uses: >-  # v5.6.2
          mikepenz/action-junit-report@cf701569b05ccdd861a76b8607a66d76f6fd4857
        if: always()
        with:
          report_paths: ${{ steps.test.outputs.junit_report }}

  language-files-up-to-date:
    name: Ensure language files are up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enabled Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Compile assets
        run: yarn build

      - uses: >-  # v4.0.2
          holyhope/test-wordpress-languages-github-action@8ed87ecf3a8eb1824d3f62b450d0cb9e28890ec9
        id: languages
        with:
          slug: customer-data
          fail_on_warning: false
          exclude: |-
            .git
            .github
            .yarn
            node_modules
            src
            tests
            vendor

      - uses: actions/upload-artifact@v4
        if: always() && steps.languages.outputs.patch_path != ''
        with:
          name: language-patch
          path: ${{ steps.languages.outputs.patch_path }}
